// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class RefreshToken
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateTime ExpirationTime { get; set; }

    public DateTime? Revoked { get; set; }

    public string RevokedByIp { get; set; }

    public string ReplacedByToken { get; set; }

    public string Token { get; set; }

    public DateTime Created { get; set; }

    public string CreatedByIp { get; set; }

    public virtual User User { get; set; }
}