// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class UserPermission
{
    public int UserPermissionId { get; set; }

    public int UserId { get; set; }

    public int PermissionId { get; set; }

    public int AssignedBy { get; set; }

    public virtual User AssignedByNavigation { get; set; }

    public virtual Permission Permission { get; set; }

    public virtual User User { get; set; }
}